; Auto-generated. Do not edit!


(cl:in-package proyecto_final-msg)


;//! \htmlinclude HandResult.msg.html

(cl:defclass <HandResult> (roslisp-msg-protocol:ros-message)
  ((hand_data
    :reader hand_data
    :initarg :hand_data
    :type (cl:vector proyecto_final-msg:HandData)
   :initform (cl:make-array 0 :element-type 'proyecto_final-msg:HandData :initial-element (cl:make-instance 'proyecto_final-msg:HandData))))
)

(cl:defclass HandResult (<HandResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HandResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HandResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name proyecto_final-msg:<HandResult> is deprecated: use proyecto_final-msg:HandResult instead.")))

(cl:ensure-generic-function 'hand_data-val :lambda-list '(m))
(cl:defmethod hand_data-val ((m <HandResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader proyecto_final-msg:hand_data-val is deprecated.  Use proyecto_final-msg:hand_data instead.")
  (hand_data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HandResult>) ostream)
  "Serializes a message object of type '<HandResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'hand_data))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'hand_data))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HandResult>) istream)
  "Deserializes a message object of type '<HandResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'hand_data) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'hand_data)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'proyecto_final-msg:HandData))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HandResult>)))
  "Returns string type for a message object of type '<HandResult>"
  "proyecto_final/HandResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HandResult)))
  "Returns string type for a message object of type 'HandResult"
  "proyecto_final/HandResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HandResult>)))
  "Returns md5sum for a message object of type '<HandResult>"
  "2780ed3d510972b1ad13ff43244bdd9c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HandResult)))
  "Returns md5sum for a message object of type 'HandResult"
  "2780ed3d510972b1ad13ff43244bdd9c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HandResult>)))
  "Returns full string definition for message of type '<HandResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%HandData[] hand_data~%~%================================================================================~%MSG: proyecto_final/HandData~%float32 x~%float32 y~%float32 z~%bool is_open~%bool is_peace~%bool hand_detected~%bool is_dino~%bool is_dislike~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HandResult)))
  "Returns full string definition for message of type 'HandResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%HandData[] hand_data~%~%================================================================================~%MSG: proyecto_final/HandData~%float32 x~%float32 y~%float32 z~%bool is_open~%bool is_peace~%bool hand_detected~%bool is_dino~%bool is_dislike~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HandResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'hand_data) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HandResult>))
  "Converts a ROS message object to a list"
  (cl:list 'HandResult
    (cl:cons ':hand_data (hand_data msg))
))
