; Auto-generated. Do not edit!


(cl:in-package proyecto_final-msg)


;//! \htmlinclude RLResult.msg.html

(cl:defclass <RLResult> (roslisp-msg-protocol:ros-message)
  ((cubes_correct_order
    :reader cubes_correct_order
    :initarg :cubes_correct_order
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0)))
)

(cl:defclass RLResult (<RLResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RLResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RLResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name proyecto_final-msg:<RLResult> is deprecated: use proyecto_final-msg:RLResult instead.")))

(cl:ensure-generic-function 'cubes_correct_order-val :lambda-list '(m))
(cl:defmethod cubes_correct_order-val ((m <RLResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader proyecto_final-msg:cubes_correct_order-val is deprecated.  Use proyecto_final-msg:cubes_correct_order instead.")
  (cubes_correct_order m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RLResult>) ostream)
  "Serializes a message object of type '<RLResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'cubes_correct_order))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    ))
   (cl:slot-value msg 'cubes_correct_order))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RLResult>) istream)
  "Deserializes a message object of type '<RLResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'cubes_correct_order) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'cubes_correct_order)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RLResult>)))
  "Returns string type for a message object of type '<RLResult>"
  "proyecto_final/RLResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RLResult)))
  "Returns string type for a message object of type 'RLResult"
  "proyecto_final/RLResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RLResult>)))
  "Returns md5sum for a message object of type '<RLResult>"
  "26becb1b8dd035f9909bdbcbd752bc80")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RLResult)))
  "Returns md5sum for a message object of type 'RLResult"
  "26becb1b8dd035f9909bdbcbd752bc80")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RLResult>)))
  "Returns full string definition for message of type '<RLResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int8[] cubes_correct_order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RLResult)))
  "Returns full string definition for message of type 'RLResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int8[] cubes_correct_order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RLResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'cubes_correct_order) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RLResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RLResult
    (cl:cons ':cubes_correct_order (cubes_correct_order msg))
))
