# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from proyecto_final/HandResult.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import proyecto_final.msg

class HandResult(genpy.Message):
  _md5sum = "2780ed3d510972b1ad13ff43244bdd9c"
  _type = "proyecto_final/HandResult"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#result definition
HandData[] hand_data

================================================================================
MSG: proyecto_final/HandData
float32 x
float32 y
float32 z
bool is_open
bool is_peace
bool hand_detected
bool is_dino
bool is_dislike
"""
  __slots__ = ['hand_data']
  _slot_types = ['proyecto_final/HandData[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hand_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HandResult, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.hand_data is None:
        self.hand_data = []
    else:
      self.hand_data = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.hand_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.hand_data:
        _x = val1
        buff.write(_get_struct_3f5B().pack(_x.x, _x.y, _x.z, _x.is_open, _x.is_peace, _x.hand_detected, _x.is_dino, _x.is_dislike))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.hand_data is None:
        self.hand_data = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.hand_data = []
      for i in range(0, length):
        val1 = proyecto_final.msg.HandData()
        _x = val1
        start = end
        end += 17
        (_x.x, _x.y, _x.z, _x.is_open, _x.is_peace, _x.hand_detected, _x.is_dino, _x.is_dislike,) = _get_struct_3f5B().unpack(str[start:end])
        val1.is_open = bool(val1.is_open)
        val1.is_peace = bool(val1.is_peace)
        val1.hand_detected = bool(val1.hand_detected)
        val1.is_dino = bool(val1.is_dino)
        val1.is_dislike = bool(val1.is_dislike)
        self.hand_data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.hand_data)
      buff.write(_struct_I.pack(length))
      for val1 in self.hand_data:
        _x = val1
        buff.write(_get_struct_3f5B().pack(_x.x, _x.y, _x.z, _x.is_open, _x.is_peace, _x.hand_detected, _x.is_dino, _x.is_dislike))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.hand_data is None:
        self.hand_data = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.hand_data = []
      for i in range(0, length):
        val1 = proyecto_final.msg.HandData()
        _x = val1
        start = end
        end += 17
        (_x.x, _x.y, _x.z, _x.is_open, _x.is_peace, _x.hand_detected, _x.is_dino, _x.is_dislike,) = _get_struct_3f5B().unpack(str[start:end])
        val1.is_open = bool(val1.is_open)
        val1.is_peace = bool(val1.is_peace)
        val1.hand_detected = bool(val1.hand_detected)
        val1.is_dino = bool(val1.is_dino)
        val1.is_dislike = bool(val1.is_dislike)
        self.hand_data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f5B = None
def _get_struct_3f5B():
    global _struct_3f5B
    if _struct_3f5B is None:
        _struct_3f5B = struct.Struct("<3f5B")
    return _struct_3f5B
