// Generated by gencpp from file proyecto_final/CubosResult.msg
// DO NOT EDIT!


#ifndef PROYECTO_FINAL_MESSAGE_CUBOSRESULT_H
#define PROYECTO_FINAL_MESSAGE_CUBOSRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <proyecto_final/IdCubos.h>

namespace proyecto_final
{
template <class ContainerAllocator>
struct CubosResult_
{
  typedef CubosResult_<ContainerAllocator> Type;

  CubosResult_()
    : cubes_position()
    , color_counter()  {
    }
  CubosResult_(const ContainerAllocator& _alloc)
    : cubes_position(_alloc)
    , color_counter(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::proyecto_final::IdCubos_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::proyecto_final::IdCubos_<ContainerAllocator> >> _cubes_position_type;
  _cubes_position_type cubes_position;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _color_counter_type;
  _color_counter_type color_counter;





  typedef boost::shared_ptr< ::proyecto_final::CubosResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proyecto_final::CubosResult_<ContainerAllocator> const> ConstPtr;

}; // struct CubosResult_

typedef ::proyecto_final::CubosResult_<std::allocator<void> > CubosResult;

typedef boost::shared_ptr< ::proyecto_final::CubosResult > CubosResultPtr;
typedef boost::shared_ptr< ::proyecto_final::CubosResult const> CubosResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proyecto_final::CubosResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proyecto_final::CubosResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::proyecto_final::CubosResult_<ContainerAllocator1> & lhs, const ::proyecto_final::CubosResult_<ContainerAllocator2> & rhs)
{
  return lhs.cubes_position == rhs.cubes_position &&
    lhs.color_counter == rhs.color_counter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::proyecto_final::CubosResult_<ContainerAllocator1> & lhs, const ::proyecto_final::CubosResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace proyecto_final

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::proyecto_final::CubosResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proyecto_final::CubosResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto_final::CubosResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto_final::CubosResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto_final::CubosResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto_final::CubosResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proyecto_final::CubosResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "debac677ee83137ba7b82eb4dd288a9f";
  }

  static const char* value(const ::proyecto_final::CubosResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdebac677ee83137bULL;
  static const uint64_t static_value2 = 0xa7b82eb4dd288a9fULL;
};

template<class ContainerAllocator>
struct DataType< ::proyecto_final::CubosResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proyecto_final/CubosResult";
  }

  static const char* value(const ::proyecto_final::CubosResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proyecto_final::CubosResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"IdCubos[] cubes_position\n"
"int8[] color_counter\n"
"\n"
"================================================================================\n"
"MSG: proyecto_final/IdCubos\n"
"int8 color\n"
"geometry_msgs/Pose pose\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::proyecto_final::CubosResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proyecto_final::CubosResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cubes_position);
      stream.next(m.color_counter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CubosResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proyecto_final::CubosResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proyecto_final::CubosResult_<ContainerAllocator>& v)
  {
    s << indent << "cubes_position[]" << std::endl;
    for (size_t i = 0; i < v.cubes_position.size(); ++i)
    {
      s << indent << "  cubes_position[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::proyecto_final::IdCubos_<ContainerAllocator> >::stream(s, indent + "    ", v.cubes_position[i]);
    }
    s << indent << "color_counter[]" << std::endl;
    for (size_t i = 0; i < v.color_counter.size(); ++i)
    {
      s << indent << "  color_counter[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.color_counter[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROYECTO_FINAL_MESSAGE_CUBOSRESULT_H
