// Generated by gencpp from file proyecto_final/FigurasResult.msg
// DO NOT EDIT!


#ifndef PROYECTO_FINAL_MESSAGE_FIGURASRESULT_H
#define PROYECTO_FINAL_MESSAGE_FIGURASRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace proyecto_final
{
template <class ContainerAllocator>
struct FigurasResult_
{
  typedef FigurasResult_<ContainerAllocator> Type;

  FigurasResult_()
    : figure_3d()
    , shape_3d()  {
    }
  FigurasResult_(const ContainerAllocator& _alloc)
    : figure_3d(_alloc)
    , shape_3d(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _figure_3d_type;
  _figure_3d_type figure_3d;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _shape_3d_type;
  _shape_3d_type shape_3d;





  typedef boost::shared_ptr< ::proyecto_final::FigurasResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proyecto_final::FigurasResult_<ContainerAllocator> const> ConstPtr;

}; // struct FigurasResult_

typedef ::proyecto_final::FigurasResult_<std::allocator<void> > FigurasResult;

typedef boost::shared_ptr< ::proyecto_final::FigurasResult > FigurasResultPtr;
typedef boost::shared_ptr< ::proyecto_final::FigurasResult const> FigurasResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proyecto_final::FigurasResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proyecto_final::FigurasResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::proyecto_final::FigurasResult_<ContainerAllocator1> & lhs, const ::proyecto_final::FigurasResult_<ContainerAllocator2> & rhs)
{
  return lhs.figure_3d == rhs.figure_3d &&
    lhs.shape_3d == rhs.shape_3d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::proyecto_final::FigurasResult_<ContainerAllocator1> & lhs, const ::proyecto_final::FigurasResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace proyecto_final

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::proyecto_final::FigurasResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proyecto_final::FigurasResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto_final::FigurasResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto_final::FigurasResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto_final::FigurasResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto_final::FigurasResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proyecto_final::FigurasResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2dd48b8210a611fb9aa995a1d0cf957d";
  }

  static const char* value(const ::proyecto_final::FigurasResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2dd48b8210a611fbULL;
  static const uint64_t static_value2 = 0x9aa995a1d0cf957dULL;
};

template<class ContainerAllocator>
struct DataType< ::proyecto_final::FigurasResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proyecto_final/FigurasResult";
  }

  static const char* value(const ::proyecto_final::FigurasResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proyecto_final::FigurasResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result\n"
"int8[] figure_3d\n"
"int8[] shape_3d\n"
;
  }

  static const char* value(const ::proyecto_final::FigurasResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proyecto_final::FigurasResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.figure_3d);
      stream.next(m.shape_3d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FigurasResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proyecto_final::FigurasResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proyecto_final::FigurasResult_<ContainerAllocator>& v)
  {
    s << indent << "figure_3d[]" << std::endl;
    for (size_t i = 0; i < v.figure_3d.size(); ++i)
    {
      s << indent << "  figure_3d[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.figure_3d[i]);
    }
    s << indent << "shape_3d[]" << std::endl;
    for (size_t i = 0; i < v.shape_3d.size(); ++i)
    {
      s << indent << "  shape_3d[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.shape_3d[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROYECTO_FINAL_MESSAGE_FIGURASRESULT_H
