// Generated by gencpp from file proyecto_final/RLResult.msg
// DO NOT EDIT!


#ifndef PROYECTO_FINAL_MESSAGE_RLRESULT_H
#define PROYECTO_FINAL_MESSAGE_RLRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace proyecto_final
{
template <class ContainerAllocator>
struct RLResult_
{
  typedef RLResult_<ContainerAllocator> Type;

  RLResult_()
    : cubes_correct_order()  {
    }
  RLResult_(const ContainerAllocator& _alloc)
    : cubes_correct_order(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _cubes_correct_order_type;
  _cubes_correct_order_type cubes_correct_order;





  typedef boost::shared_ptr< ::proyecto_final::RLResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proyecto_final::RLResult_<ContainerAllocator> const> ConstPtr;

}; // struct RLResult_

typedef ::proyecto_final::RLResult_<std::allocator<void> > RLResult;

typedef boost::shared_ptr< ::proyecto_final::RLResult > RLResultPtr;
typedef boost::shared_ptr< ::proyecto_final::RLResult const> RLResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proyecto_final::RLResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proyecto_final::RLResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::proyecto_final::RLResult_<ContainerAllocator1> & lhs, const ::proyecto_final::RLResult_<ContainerAllocator2> & rhs)
{
  return lhs.cubes_correct_order == rhs.cubes_correct_order;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::proyecto_final::RLResult_<ContainerAllocator1> & lhs, const ::proyecto_final::RLResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace proyecto_final

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::proyecto_final::RLResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proyecto_final::RLResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto_final::RLResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto_final::RLResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto_final::RLResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto_final::RLResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proyecto_final::RLResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26becb1b8dd035f9909bdbcbd752bc80";
  }

  static const char* value(const ::proyecto_final::RLResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26becb1b8dd035f9ULL;
  static const uint64_t static_value2 = 0x909bdbcbd752bc80ULL;
};

template<class ContainerAllocator>
struct DataType< ::proyecto_final::RLResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proyecto_final/RLResult";
  }

  static const char* value(const ::proyecto_final::RLResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proyecto_final::RLResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int8[] cubes_correct_order\n"
;
  }

  static const char* value(const ::proyecto_final::RLResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proyecto_final::RLResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cubes_correct_order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proyecto_final::RLResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proyecto_final::RLResult_<ContainerAllocator>& v)
  {
    s << indent << "cubes_correct_order[]" << std::endl;
    for (size_t i = 0; i < v.cubes_correct_order.size(); ++i)
    {
      s << indent << "  cubes_correct_order[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.cubes_correct_order[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROYECTO_FINAL_MESSAGE_RLRESULT_H
