// Auto-generated. Do not edit!

// (in-package proyecto_final.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let IdCubos = require('./IdCubos.js');

//-----------------------------------------------------------

class CubosResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.cubes_position = null;
      this.color_counter = null;
    }
    else {
      if (initObj.hasOwnProperty('cubes_position')) {
        this.cubes_position = initObj.cubes_position
      }
      else {
        this.cubes_position = [];
      }
      if (initObj.hasOwnProperty('color_counter')) {
        this.color_counter = initObj.color_counter
      }
      else {
        this.color_counter = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CubosResult
    // Serialize message field [cubes_position]
    // Serialize the length for message field [cubes_position]
    bufferOffset = _serializer.uint32(obj.cubes_position.length, buffer, bufferOffset);
    obj.cubes_position.forEach((val) => {
      bufferOffset = IdCubos.serialize(val, buffer, bufferOffset);
    });
    // Serialize message field [color_counter]
    bufferOffset = _arraySerializer.int8(obj.color_counter, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CubosResult
    let len;
    let data = new CubosResult(null);
    // Deserialize message field [cubes_position]
    // Deserialize array length for message field [cubes_position]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.cubes_position = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.cubes_position[i] = IdCubos.deserialize(buffer, bufferOffset)
    }
    // Deserialize message field [color_counter]
    data.color_counter = _arrayDeserializer.int8(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 57 * object.cubes_position.length;
    length += object.color_counter.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'proyecto_final/CubosResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'debac677ee83137ba7b82eb4dd288a9f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    IdCubos[] cubes_position
    int8[] color_counter
    
    ================================================================================
    MSG: proyecto_final/IdCubos
    int8 color
    geometry_msgs/Pose pose
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CubosResult(null);
    if (msg.cubes_position !== undefined) {
      resolved.cubes_position = new Array(msg.cubes_position.length);
      for (let i = 0; i < resolved.cubes_position.length; ++i) {
        resolved.cubes_position[i] = IdCubos.Resolve(msg.cubes_position[i]);
      }
    }
    else {
      resolved.cubes_position = []
    }

    if (msg.color_counter !== undefined) {
      resolved.color_counter = msg.color_counter;
    }
    else {
      resolved.color_counter = []
    }

    return resolved;
    }
};

module.exports = CubosResult;
