// Auto-generated. Do not edit!

// (in-package proyecto_final.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FigurasResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.figure_3d = null;
      this.shape_3d = null;
    }
    else {
      if (initObj.hasOwnProperty('figure_3d')) {
        this.figure_3d = initObj.figure_3d
      }
      else {
        this.figure_3d = [];
      }
      if (initObj.hasOwnProperty('shape_3d')) {
        this.shape_3d = initObj.shape_3d
      }
      else {
        this.shape_3d = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FigurasResult
    // Serialize message field [figure_3d]
    bufferOffset = _arraySerializer.int8(obj.figure_3d, buffer, bufferOffset, null);
    // Serialize message field [shape_3d]
    bufferOffset = _arraySerializer.int8(obj.shape_3d, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FigurasResult
    let len;
    let data = new FigurasResult(null);
    // Deserialize message field [figure_3d]
    data.figure_3d = _arrayDeserializer.int8(buffer, bufferOffset, null)
    // Deserialize message field [shape_3d]
    data.shape_3d = _arrayDeserializer.int8(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.figure_3d.length;
    length += object.shape_3d.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'proyecto_final/FigurasResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2dd48b8210a611fb9aa995a1d0cf957d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    int8[] figure_3d
    int8[] shape_3d
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FigurasResult(null);
    if (msg.figure_3d !== undefined) {
      resolved.figure_3d = msg.figure_3d;
    }
    else {
      resolved.figure_3d = []
    }

    if (msg.shape_3d !== undefined) {
      resolved.shape_3d = msg.shape_3d;
    }
    else {
      resolved.shape_3d = []
    }

    return resolved;
    }
};

module.exports = FigurasResult;
