// Auto-generated. Do not edit!

// (in-package proyecto_final.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class RLResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.cubes_correct_order = null;
    }
    else {
      if (initObj.hasOwnProperty('cubes_correct_order')) {
        this.cubes_correct_order = initObj.cubes_correct_order
      }
      else {
        this.cubes_correct_order = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RLResult
    // Serialize message field [cubes_correct_order]
    bufferOffset = _arraySerializer.int8(obj.cubes_correct_order, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RLResult
    let len;
    let data = new RLResult(null);
    // Deserialize message field [cubes_correct_order]
    data.cubes_correct_order = _arrayDeserializer.int8(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.cubes_correct_order.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'proyecto_final/RLResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '26becb1b8dd035f9909bdbcbd752bc80';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    int8[] cubes_correct_order
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RLResult(null);
    if (msg.cubes_correct_order !== undefined) {
      resolved.cubes_correct_order = msg.cubes_correct_order;
    }
    else {
      resolved.cubes_correct_order = []
    }

    return resolved;
    }
};

module.exports = RLResult;
